FROM python:3.8-slim-buster

RUN apt-get -y update && apt-get -y install curl

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . /app

RUN rm .env

CMD ["python3", "-m", "pytest", "tests/"]